function openPurchases(){if(!isAdmin())return;renderPurchases();$('purchasesModal').classList.add('on')}window.openPurchases=openPurchases;
function renderPurchases(){if(!$('purchasesList'))return;var a=db.buys.slice().sort(function(a,b){return String(b.date||'').localeCompare(String(a.date||''))});$('purchasesList').innerHTML=a.length?a.map(function(o){var s=supplier(o.party);return '<div class="row"><div class="rowtop"><div><h4>'+esc(s?s.name:'Compra')+'</h4><div class="meta">'+esc(o.date||'')+' · '+(o.items||[]).length+' item(ns)</div></div><div class="value">'+money(orderTotal(o))+'</div></div><div class="actions"><button class="danger" onclick="deleteEntity(\'buys\',\''+o.id+'\')">Excluir</button></div></div>'}).join(''):'<div class="empty">Nenhuma compra.</div>'}
function openPurchaseForm(){if(!isAdmin())return;$('bSupplier').innerHTML='<option value="">Selecione...</option>'+db.suppliers.map(function(s){return '<option value="'+esc(s.id)+'">'+esc(s.name)+'</option>'}).join('');$('bDate').value=today();$('bPay').value='Pix';$('bStatus').value='paid';$('bNotes').value='';$('bItems').innerHTML='';addBuyItem();calcBuy();$('purchaseForm').classList.add('on')}window.openPurchaseForm=openPurchaseForm;
function addBuyItem(){var d=document.createElement('div');d.className='item';var opts=db.products.map(function(p){return '<option value="'+esc(p.id)+'">'+esc(p.name)+'</option>'}).join('');d.innerHTML='<div class="itemgrid"><label class="field">Produto<select class="bp"><option value="">Selecione...</option>'+opts+'</select></label><label class="field">Qtd.<input class="bq" type="number" min="0.01" step="0.01" value="1"></label><label class="field">Custo<input class="bv" type="number" min="0" step="0.01" value="0"></label><button type="button" class="secondary remove">Remover</button></div>';d.querySelector('.bp').onchange=function(e){var p=product(e.target.value);d.querySelector('.bv').value=p?Number(p.cost||0):0;calcBuy()};d.querySelectorAll('input').forEach(function(i){i.oninput=calcBuy});d.querySelector('.remove').onclick=function(){d.remove();calcBuy()};$('bItems').appendChild(d)}window.addBuyItem=addBuyItem;
function calcBuy(){var n=0;document.querySelectorAll('#bItems .item').forEach(function(d){n+=(Number(d.querySelector('.bq').value)||0)*(Number(d.querySelector('.bv').value)||0)});$('bTotal').textContent=money(n)}window.calcBuy=calcBuy;
async function savePurchase(){var items=Array.prototype.slice.call(document.querySelectorAll('#bItems .item')).map(function(d){return {productId:d.querySelector('.bp').value,qty:Number(d.querySelector('.bq').value)||0,price:Number(d.querySelector('.bv').value)||0}}).filter(function(i){return i.productId&&i.qty>0});if(!items.length){alert('Adicione produtos.');return}var buy={id:uid(),date:$('bDate').value||today(),party:$('bSupplier').value,pay:$('bPay').value,status:$('bStatus').value,notes:$('bNotes').value,items:items};try{await api('append_buy',{buy:buy});closeModal('purchaseForm');await pull(false);renderPurchases()}catch(e){alert(e.message)}}window.savePurchase=savePurchase;

function openSuppliers(){if(!isAdmin())return;renderSuppliers();$('suppliersModal').classList.add('on')}window.openSuppliers=openSuppliers;
function renderSuppliers(){if(!$('suppliersList'))return;$('suppliersList').innerHTML=db.suppliers.length?db.suppliers.slice().sort(function(a,b){return String(a.name).localeCompare(String(b.name))}).map(function(s){return '<div class="row"><div class="rowtop"><div><h4>'+esc(s.name)+'</h4><div class="meta">'+esc(s.phone||'')+(s.address?' · '+esc(s.address):'')+'</div></div></div><div class="actions"><button class="secondary" onclick="openSupplier(\''+s.id+'\')">Editar</button><button class="danger" onclick="deleteEntity(\'suppliers\',\''+s.id+'\')">Excluir</button></div></div>'}).join(''):'<div class="empty">Nenhum fornecedor.</div>'}
function openSupplier(id){if(!isAdmin())return;id=id||'';editSupplierId=id;var s=supplier(id)||{};$('supplierTitle').textContent=id?'Editar fornecedor':'Novo fornecedor';$('sName').value=s.name||'';$('sPhone').value=s.phone||'';$('sAddress').value=s.address||'';$('supplierForm').classList.add('on')}window.openSupplier=openSupplier;
async function saveSupplier(){var name=$('sName').value.trim();if(!name){alert('Informe o nome.');return}var entity={id:editSupplierId||uid(),name:name,phone:$('sPhone').value.trim(),address:$('sAddress').value.trim()};try{await api('upsert_entity',{key:'suppliers',entity:entity});closeModal('supplierForm');await pull(false);renderSuppliers()}catch(e){alert(e.message)}}window.saveSupplier=saveSupplier;

async function openUsers(){if(!isAdmin())return;$('usersModal').classList.add('on');await renderUsers()}window.openUsers=openUsers;
async function renderUsers(){try{var j=await api('list_users');$('usersList').innerHTML=(j.users||[]).map(function(u){return '<div class="row"><div class="rowtop"><div><h4>'+esc(u.username)+'</h4><div class="meta">'+(u.role==='admin'?'Administrador':'Usuário')+' · '+(u.enabled?'Ativo':'Bloqueado')+'</div></div>'+(u.username===session.user.username?'<span class="pill">Você</span>':'')+'</div>'+(u.username!==session.user.username?'<div class="actions"><button class="secondary" onclick="setUser(\''+u.id+'\','+(!u.enabled)+')">'+(u.enabled?'Bloquear':'Ativar')+'</button></div>':'')+'</div>'}).join('')}catch(e){alert(e.message)}}
async function saveUser(){var u=$('uName').value.trim(),p=$('uPass').value,r=$('uRole').value;if(u.length<2||p.length<6){alert('Usuário com pelo menos 2 caracteres e senha com pelo menos 6.');return}try{await api('create_user',{username:u,password:p,role:r});$('uName').value='';$('uPass').value='';await renderUsers()}catch(e){alert(e.message)}}window.saveUser=saveUser;
async function setUser(id,enabled){try{await api('set_user_enabled',{user_id:id,enabled:enabled});await renderUsers()}catch(e){alert(e.message)}}window.setUser=setUser;

function receipt(id,kind){var o=db.sales.find(function(x){return x.id===id});if(!o)return;var c=customer(o.party),title=kind==='quote'?'ORÇAMENTO':'PEDIDO / RECIBO',rows=(o.items||[]).map(function(i){var p=product(i.productId);return '<tr><td>'+esc(p?p.name:'Produto')+'</td><td>'+i.qty+'</td><td>'+money(i.price)+'</td><td>'+money(Number(i.qty)*Number(i.price))+'</td></tr>'}).join('');var w=window.open('','_blank');if(!w){alert('Permita pop-ups para gerar o documento.');return}w.document.write('<html><head><meta name="viewport" content="width=device-width"><style>body{font-family:Arial;padding:22px;color:#111}table{width:100%;border-collapse:collapse;margin-top:20px}th,td{border-bottom:1px solid #ddd;padding:9px 5px;text-align:left}.total{text-align:right;font-size:20px;font-weight:bold;margin-top:18px}</style></head><body><h2>'+title+'</h2><div>Data: '+esc(o.date)+'<br>Cliente: '+esc(c?c.name:'Não informado')+'<br>Pagamento: '+esc(o.pay)+' · '+(o.status==='paid'?'Pago':'Pendente')+'</div><table><thead><tr><th>Item</th><th>Qtd.</th><th>Unit.</th><th>Total</th></tr></thead><tbody>'+rows+'</tbody></table><div class="total">Total: '+money(orderTotal(o))+'</div><p>'+esc(o.notes||'')+'</p></body></html>');w.document.close();setTimeout(function(){try{w.print()}catch(e){}},350)}window.receipt=receipt;

async function boot(){
  try{session=JSON.parse(localStorage.getItem(SESSION_KEY)||'null')}catch(e){session=null}
  initPeriod();
  if(session&&session.token){$('loginScreen').classList.remove('on');try{await afterLogin()}catch(e){console.error(e);await logout()}}
  else{$('loginScreen').classList.add('on');setSync('Aguardando login')}
}
window.__gestaoAppReady=true;
boot();
