function renderAll(){renderHome();renderOrders();renderCustomers();renderProducts();if(isAdmin()){renderPurchases();renderSuppliers()}}
function renderHome(){
  var d=today(),m=d.slice(0,7),st=db.sales.filter(function(o){return o.date===d}),sm=db.sales.filter(function(o){return String(o.date||'').indexOf(m)===0});
  var td=st.reduce(function(s,o){return s+orderTotal(o)},0),tm=sm.reduce(function(s,o){return s+orderTotal(o)},0);
  $('homeToday').textContent=money(td);$('homeMonth').textContent=money(tm);$('homeCount').textContent=String(sm.length);$('homeTicket').textContent=money(sm.length?tm/sm.length:0);
  var last=db.sales.slice().sort(function(a,b){return String(b.date||'').localeCompare(String(a.date||''))}).slice(0,5);
  $('homeOrders').innerHTML=last.length?last.map(orderCard).join(''):'<div class="empty">Nenhum pedido registrado.</div>';
}
function orderCard(o){
  var c=customer(o.party),who=isAdmin()&&o.createdBy?' · '+esc(o.createdBy):'';
  return '<div class="row"><div class="rowtop"><div><h4>'+esc(c?c.name:'Cliente não informado')+'</h4><div class="meta">'+esc(o.date||'')+' · '+(o.items||[]).length+' item(ns)'+who+'</div></div><div style="text-align:right"><div class="value">'+money(orderTotal(o))+'</div><span class="pill">'+(o.status==='paid'?'Pago':'Pendente')+'</span></div></div><div class="actions"><button class="secondary" onclick="receipt(\''+o.id+'\',\'receipt\')">Recibo</button><button class="secondary" onclick="receipt(\''+o.id+'\',\'quote\')">Orçamento</button>'+(isAdmin()?'<button class="danger" onclick="deleteEntity(\'sales\',\''+o.id+'\')">Excluir</button>':'')+'</div></div>';
}
function initPeriod(){if(!$('orderPeriod'))return;$('orderPeriod').value='month';$('periodValue').type='month';$('periodValue').value=today().slice(0,7);$('periodLabel').firstChild.nodeValue='Mês'}
function periodChanged(){var mode=$('orderPeriod').value;if(mode==='day'){$('periodValue').type='date';$('periodValue').value=today();$('periodLabel').firstChild.nodeValue='Dia'}else if(mode==='year'){$('periodValue').type='number';$('periodValue').min='2000';$('periodValue').max='2100';$('periodValue').value=String(new Date().getFullYear());$('periodLabel').firstChild.nodeValue='Ano'}else{$('periodValue').type='month';$('periodValue').value=today().slice(0,7);$('periodLabel').firstChild.nodeValue='Mês'}renderOrders()}
window.periodChanged=periodChanged;
function filteredOrders(){var mode=$('orderPeriod').value,v=$('periodValue').value,q=$('orderSearch').value.trim().toLowerCase();return db.sales.filter(function(o){var d=String(o.date||''),dateOk=mode==='day'?d===v:mode==='year'?d.indexOf(v+'-')===0:d.indexOf(v)===0;var c=customer(o.party),name=String(c?c.name:'').toLowerCase();return dateOk&&(!q||name.indexOf(q)>=0)}).sort(function(a,b){return String(b.date||'').localeCompare(String(a.date||''))})}
function renderOrders(){if(!$('ordersList'))return;var a=filteredOrders();$('ordersTotal').textContent=money(a.reduce(function(s,o){return s+orderTotal(o)},0));$('ordersCount').textContent=String(a.length);$('ordersList').innerHTML=a.length?a.map(orderCard).join(''):'<div class="empty">Nenhum pedido nesse período.</div>'}
window.renderOrders=renderOrders;

function openOrder(){
  $('oCustomer').innerHTML='<option value="">Selecione o cliente...</option>'+db.customers.slice().sort(function(a,b){return String(a.name).localeCompare(String(b.name))}).map(function(c){return '<option value="'+esc(c.id)+'">'+esc(c.name)+'</option>'}).join('');
  $('oDate').value=today();$('oPay').value='Pix';$('oStatus').value='paid';$('oFulfill').value='pickup';$('oAddress').value='';$('oAddressWrap').style.display='none';$('oNotes').value='';$('oItems').innerHTML='';addOrderItem();calcOrder();$('orderModal').classList.add('on');
}
window.openOrder=openOrder;
function toggleOrderAddress(){$('oAddressWrap').style.display=$('oFulfill').value==='delivery'?'block':'none'}window.toggleOrderAddress=toggleOrderAddress;
function addOrderItem(){var d=document.createElement('div');d.className='item';var opts=db.products.slice().sort(function(a,b){return String(a.name).localeCompare(String(b.name))}).map(function(p){return '<option value="'+esc(p.id)+'">'+esc(p.name)+(p.brand?' · '+esc(p.brand):'')+'</option>'}).join('');d.innerHTML='<div class="itemgrid"><label class="field">Produto<select class="ip"><option value="">Selecione...</option>'+opts+'</select></label><label class="field">Qtd.<input class="iq" type="number" min="0.01" step="0.01" value="1"></label><label class="field">Preço<input class="iv" type="number" min="0" step="0.01" value="0"></label><button type="button" class="secondary remove">Remover</button></div>';d.querySelector('.ip').onchange=function(e){var p=product(e.target.value);d.querySelector('.iv').value=p?Number(p.price||0):0;calcOrder()};d.querySelectorAll('input').forEach(function(i){i.oninput=calcOrder});d.querySelector('.remove').onclick=function(){d.remove();calcOrder()};$('oItems').appendChild(d)}window.addOrderItem=addOrderItem;
function calcOrder(){var n=0;document.querySelectorAll('#oItems .item').forEach(function(d){n+=(Number(d.querySelector('.iq').value)||0)*(Number(d.querySelector('.iv').value)||0)});$('oTotal').textContent=money(n)}window.calcOrder=calcOrder;
async function saveOrder(){var items=Array.prototype.slice.call(document.querySelectorAll('#oItems .item')).map(function(d){return {productId:d.querySelector('.ip').value,qty:Number(d.querySelector('.iq').value)||0,price:Number(d.querySelector('.iv').value)||0}}).filter(function(i){return i.productId&&i.qty>0});if(!$('oCustomer').value){alert('Selecione um cliente.');return}if(!items.length){alert('Adicione pelo menos um produto.');return}var o={id:uid(),date:$('oDate').value||today(),party:$('oCustomer').value,pay:$('oPay').value,status:$('oStatus').value,fulfill:$('oFulfill').value,address:$('oAddress').value,notes:$('oNotes').value,items:items};try{setSync('Salvando pedido...');await api('add_sale',{sale:o});closeModal('orderModal');await pull(false);setSync('Pedido salvo','ok');go('orders')}catch(e){alert(e.message);setSync('Erro ao salvar','bad')}}window.saveOrder=saveOrder;

function renderCustomers(){var q=$('customerSearch').value.trim().toLowerCase();var a=db.customers.filter(function(c){return !q||[c.name,c.phone,c.address].join(' ').toLowerCase().indexOf(q)>=0}).sort(function(a,b){return String(a.name).localeCompare(String(b.name))});$('customersList').innerHTML=a.length?a.map(function(c){return '<div class="row" onclick="openCustomerDetail(\''+c.id+'\')"><div class="rowtop"><div><h4>'+esc(c.name)+'</h4><div class="meta">'+esc(c.phone||'Sem telefone')+(c.address?' · '+esc(c.address):'')+'</div></div><span class="pill">Ver histórico</span></div></div>'}).join(''):'<div class="empty">Nenhum cliente encontrado.</div>'}window.renderCustomers=renderCustomers;
function openCustomer(id){id=id||'';if(id&&!isAdmin()){alert('Apenas o administrador pode editar clientes existentes.');return}editCustomerId=id;var c=customer(id)||{};$('customerTitle').textContent=id?'Editar cliente':'Novo cliente';$('cName').value=c.name||'';$('cPhone').value=c.phone||'';$('cAddress').value=c.address||'';$('cBalance').value=Number(c.balance||0);var f=$('cBalance').closest('.field');if(f)f.style.display=isAdmin()?'block':'none';$('customerModal').classList.add('on')}window.openCustomer=openCustomer;
async function saveCustomer(){var name=$('cName').value.trim();if(!name){alert('Informe o nome do cliente.');return}var entity={id:editCustomerId||uid(),name:name,phone:$('cPhone').value.trim(),address:$('cAddress').value.trim(),balance:isAdmin()?Number($('cBalance').value)||0:0};try{setSync('Salvando cliente...');if(editCustomerId){if(!isAdmin()){alert('Sem permissão.');return}await api('upsert_entity',{key:'customers',entity:entity})}else await api('add_customer',{customer:entity});closeModal('customerModal');await pull(false);setSync('Cliente salvo','ok')}catch(e){alert(e.message);setSync('Erro ao salvar','bad')}}window.saveCustomer=saveCustomer;
function openCustomerDetail(id){currentCustomerId=id;var c=customer(id);if(!c)return;$('cdName').textContent=c.name;$('cdPhone').textContent=c.phone?'Telefone: '+c.phone:'Sem telefone';$('cdAddress').textContent=c.address?'Endereço: '+c.address:'Sem endereço';$('cdEdit').style.display=isAdmin()?'block':'none';var a=db.sales.filter(function(o){return o.party===id}).sort(function(a,b){return String(b.date||'').localeCompare(String(a.date||''))});$('cdOrders').innerHTML=a.length?a.map(orderCard).join(''):'<div class="empty">Nenhum pedido desse cliente.</div>';$('customerDetail').classList.add('on')}window.openCustomerDetail=openCustomerDetail;
function editCurrentCustomer(){closeModal('customerDetail');openCustomer(currentCustomerId)}window.editCurrentCustomer=editCurrentCustomer;

function renderProducts(){var q=$('productSearch').value.trim().toLowerCase();var a=db.products.filter(function(p){return !q||[p.name,p.brand].join(' ').toLowerCase().indexOf(q)>=0}).sort(function(a,b){return String(a.name).localeCompare(String(b.name))});$('addProductBtn').style.display=isAdmin()?'block':'none';$('productsList').innerHTML=a.length?a.map(function(p){return '<div class="product"><h4>'+esc(p.name)+'</h4><div class="meta">'+esc(p.brand||'Sem marca')+(isAdmin()?'<br>Custo: '+money(p.cost):'')+'</div><div class="price">'+money(p.price)+'</div>'+(isAdmin()?'<div class="actions"><button class="secondary" onclick="openProduct(\''+p.id+'\')">Editar</button><button class="danger" onclick="deleteEntity(\'products\',\''+p.id+'\')">Excluir</button></div>':'')+'</div>'}).join(''):'<div class="empty" style="grid-column:1/-1">Nenhum produto encontrado.</div>'}window.renderProducts=renderProducts;
function openProduct(id){if(!isAdmin()){alert('Apenas administradores cadastram produtos.');return}id=id||'';editProductId=id;var p=product(id)||{};$('productTitle').textContent=id?'Editar produto':'Novo produto';$('pName').value=p.name||'';$('pBrand').value=p.brand||'';$('pCost').value=Number(p.cost||0);$('pPrice').value=Number(p.price||0);$('productModal').classList.add('on')}window.openProduct=openProduct;
async function saveProduct(){if(!isAdmin())return;var name=$('pName').value.trim();if(!name){alert('Informe o nome.');return}var entity={id:editProductId||uid(),name:name,brand:$('pBrand').value.trim(),cost:Number($('pCost').value)||0,price:Number($('pPrice').value)||0};try{await api('upsert_entity',{key:'products',entity:entity});closeModal('productModal');await pull(false)}catch(e){alert(e.message)}}window.saveProduct=saveProduct;
async function deleteEntity(key,id){if(!isAdmin())return;if(!confirm('Excluir este registro?'))return;try{await api('delete_entity',{key:key,id:id});await pull(false)}catch(e){alert(e.message)}}window.deleteEntity=deleteEntity;
